### ISSUE TITLE
Windows port

### ISSUE THREAD

**Issue by adamansky** [Softmotions/ejdb#12]

**Comment by dalegaspi** [comment]
trying to get this to install on Windows 2012 and this is the error i'm getting (this is after nstalled node-gyp nan module):
```
C:\Users\Administrator>npm install ejdb
|
> ejdb@1.2.6-1 preinstall C:\Users\Administrator\node_modules\ejdb
> node platform.js preinstall

Downloading windows binaries from: https://dl.dropboxusercontent.com/u/4709222/ejdb/ejdb-1.2.4-Release-Windows-x86.tar.gz ...
File: ejdbdll\ejdb-1.2.4-Release-Windows-x86.tar.gz
...............................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
...................................................................
2196740 bytes received
Unzip archive 'ejdbdll\ejdb-1.2.4-Release-Windows-x86.tar.gz'
node-gyp ["configure","rebuild"]

C:\Users\Administrator\node_modules\ejdb>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure rebuild )  else (configure rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  ejdb_native.cc
  ejdb_logging.cc
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\ejdb_logging.cc) [C:\Users\Administrator\node_modules\ejdb\build\ejdb_native.vcxproj]
..\ejdb_native.cc(18): fatal error C1083: Cannot open include file: 'ejdb_private.h': No such file or directory [C:\Users\Administrator\node_modules\ejdb\build\ejdb_native.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "rebuild"
gyp ERR! cwd C:\Users\Administrator\node_modules\ejdb
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
node-gyp process exited with code 1
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ejdb"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! ejdb@1.2.6-1 preinstall: `node platform.js preinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ejdb@1.2.6-1 preinstall script 'node platform.js preinstall'.
npm ERR! This is most likely a problem with the ejdb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node platform.js preinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls ejdb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\npm-debug.log
```

**Comment by tyutyunkov** [comment]
We fixed building ejdb-node module for windows. Please, try install again.
